# base pet config with swin backbone

# training Parameters
epochs: 1500
lr: 0.0001 #0.0001
lr_backbone: 0.00001 #0.00001
weight_decay: 0.0001 #0.0001
clip_max_norm: 0.1 #0.01
seed: 3407 # 42, 3407
eval_freq: 5

# model parameters
backbone: swin_t
position_embedding: sine
attn_type: softmax
dec_layers: 2
dim_feedforward: 512
hidden_dim: 256
dropout: 0.0
nheads: 8
backbone_num_channels: 512 # 512
sparse_stride: 16 #16
dense_stride: 8 #8
enc_win_list: [[16, 8], [16, 8], [8, 4], [8, 4]] #[[32, 16], [32, 16], [16, 8], [16, 8]] #[[16, 8], [16, 8], [8, 4], [8, 4]]
context_patch: [64, 32] #[128, 64] #
sparse_dec_win_size: [8, 4] #[16, 8] #
dense_dec_win_size: [4, 2] #[8, 4] #
syn_bn: 0

# loss parameters
set_cost_class: 1
set_cost_point: 0.05
ce_loss_coef: 1.0
point_loss_coef: 5.0 #5.0
map_loss_coef: 1.0
eos_coef: 0.5


data_path: ignore
num_workers: 2
global_crop_ratio: 0.1
predict: origin # hxn, origin
save_ckpt_freq: 1000
augmented: False

# check:
dataset_file: Car
opt_query_con: False

### baseline setting
attn_splitter: True
Orattn: True
encoder_free: True
patch_size: 256   # patch_size = 512 originally

# debug
batch_size: 8

# zlt para for decoder and loss
opt_query_decoder: False
loss_f: prob # prob, normal
prob_map_lc: f4x # f4x, None
prob_bandwidth: dynamic # dynamic, fixed

# hfy para for backbone swin
use_spatial_attention: False
use_arc: False
upsample_strategy: 'bilinear' # dysample, bilinear
fpn_type: 'original'  # panet, original

# july stage para
matcher: 'hun' # stable, hun 
box_setting: 1 # 2 is qp from 0-1, 3?

# one key setting
one_key_hfy: False # backbone Feature
one_key_zlt: False # attnsplit, boxquery, mixedloss


output_dir: base_s2