# base pet config with swin backbone

# training Parameters
lr: 0.0001
lr_backbone: 0.00001
weight_decay: 0.0001
clip_max_norm: 0.1

epochs: 1500
seed: 3407 # 42, 3407
eval_freq: 2

# model parameters
backbone: swin_t 
position_embedding: sine
attn_type: softmax
dec_layers: 2
dim_feedforward: 512
hidden_dim: 256
dropout: 0.0
nheads: 8
backbone_num_channels: 512 # 512
sparse_stride: 16 #16
dense_stride: 8 #8
enc_win_list: [[16, 8], [16, 8], [8, 4], [8, 4]] #[[32, 16], [32, 16], [16, 8], [16, 8]] #[[16, 8], [16, 8], [8, 4], [8, 4]]
context_patch: [64, 32] #[128, 64] #[16, 16] #
sparse_dec_win_size: [8, 4] #[16, 8] #
dense_dec_win_size: [4, 2] #[8, 4] #
syn_bn: 0

# loss parameters
set_cost_class: 1
set_cost_point: 0.05
ce_loss_coef: 1.0
point_loss_coef: 5.0
map_loss_coef: 1.0
eos_coef: 0.5

# dataset parameters
dataset_file: SOY
data_path: ignore
patch_size: 256   # patch_size = 512 originally
num_workers: 2
global_crop_ratio: 0.1

predict: origin # hxn, origin
save_ckpt_freq: 1000
augmented: False
opt_query_con: False

# baseline setting
attn_splitter: True
# Orattn: True
encoder_free: True

# debug
batch_size: 16

# zlt para for decoder and loss
opt_query_decoder: False
box_setting: 1 # 2 is qp from 0-1
loss_f: normal # prob, normal
prob_map_lc: None # f4x, None

# hfy para for backbone swin
use_spatial_attention: False
use_arc: False
upsample_strategy: 'bilinear' # dysample, bilinear
fpn_type: 'original'  # panet, original

# one key setting
one_key_hfy: False # backbone Feature
one_key_zlt: True # attnsplit, boxquery, mixedloss

# july stage para
matcher: 'hun' # stable, hun 

output_dir: t_base_zlt #t_attnsplit_boxquery_mixedloss_ransize0618